Repository oracle/nosql-examples, pull requests merged in 2023-01, with the labels that each got.

#94 Create build_spec.yaml
  build_spec.yaml
Labels: OCA Verified

#99 New examples-nosql-cluster-deployment.zip
  zips/examples-nosql-cluster-deployment.zip
Labels: OCA Verified

#100 minor fix - examples-nosql-cluster-deployment
  examples-nosql-cluster-deployment/README.md
  examples-nosql-cluster-deployment/script/template_single-node-rf1.kvs
  zips/examples-nosql-cluster-deployment.zip
Labels: deploy-nosql, OCA Verified

#102 Delete package-lock.json in my-first-nest-rest-app dependencies
  examples-nosql-node-sdk/my-first-nest-rest-app/package-lock.json
Labels: dependencies, OCA Verified
